### ISSUE TITLE
Checklist for publishing the python package on pypi 

### ISSUE THREAD

**Issue by rugeli** [allen-cell-animated/cell-feature-data#105]
## Use Case

Publishing the package to pypi, here are modifications we might need:

- [ ] Users will be able to install the package directly using pip, no longer need to "make a branch or fork". Update the documentation after the changes.
- [x] Consider renaming the package from `python_dataset_creator` to  `cell_feature_data` or another suitable name 
- [ ] A github action workflow to automate publishing, and version pumping, etc 
- [x] Have users create virtual environments in a specific folder so that we can completely ignore that folder to avoid any extensive code changes
